include "/stdlib/jdk/21/jetbrains.conf"

conveyor.compatibility-level = 22
conveyor.billing-email = "andrestormenta1@gmail.com"

app {
    display-name = "Melodist"
    fsname = "melodist"
    version = "1.0.3"
    vendor = "Tarma"
    description = "Reproductor de música de escritorio"
    rdns-name = "com.example.melodist"

    vcs-url = "github.com/AndresTarma1/Melodist"
    machines = ["windows.amd64"]

    // Entrada principal de la app compilada
    inputs = [
        "composeApp/build/compose/jars/*.jar",
        {
            from = "mpv-resources/windows/libmpv-2.dll"
            to = "app/libmpv-2.dll" // Lo ponemos en la carpeta 'app' para que el sistema lo encuentre fácil
        }
    ]

    jvm {
        gui.main-class = "com.example.melodist.MainKt"
        include-all-modules = true

        modules += "java.sql"

        args = [
            "--add-modules=java.sql",
            "-XX:+EnableDynamicAgentLoading",
            "-Xmx512m",
            "-Xms128m",
            "-XX:+UseG1GC"
        ]

        // Importante para las rutas dinámicas en producción
        system-properties."compose.application.resources.dir" = "."
    }

    site {
        github {
            oauth-token = ${env.conveyor_token_melodist}
            pages-branch = "gh-pages"
        }
    }
}

windows {
    // Aquí definimos los formatos de salida
    // MSIX es el que suele dar problemas, así que ponemos EXE y MSI como prioridad
    formats = ["exe", "msi", "zip"]

    enable-exe = true
    enable-msi = true

    menu-group = "Melodist"
    desktop-shortcut = true
    per-user-install = true
    allow-custom-install-dir = true
    upgrade-uuid = "4A2F8B6C-1D3E-4F5A-B7C8-9D0E1F2A3B4C"
}

gradle.main-module = "composeApp"
