include "/stdlib/jdk/21/jetbrains.conf"

conveyor.compatibility-level = 22
conveyor.billing-email = "andrestormenta1@gmail.com"

// Comandos necesarios para el build
// 1. Creamos los Jar necesarios para el build "./gradlew packageUberJarForCurrentOS"
// 2. Ejecutamos el build "conveyor make windows-msix"
// Antes de todo eso debemos haber puesto en el env el token de github para que pueda subir a gh-pages el sitio de la app, y también haber creado el repositorio en github con el mismo nombre que la app (en este caso "Melodist")
// Por ultimo lanzamos al github "conveyor make copied-site"


// Pasos para actualizar
//Obligatorio: gradle.properties (version).
//Obligatorio: composeApp/build.gradle.kts (nativeDistributions.packageVersion).
//Obligatorio si usas Conveyor directo: conveyor.conf (app.version).
//Opcional/recomendado: texto de versión en UI (SettingsScreen) y README.md.

app {
    display-name = "Melodist"
    fsname = "melodist"
    version = "1.0.2"
    vendor = "Tarma"
    description = "Reproductor de música de escritorio"
    rdns-name = "com.example.melodist"

    vcs-url = "github.com/AndresTarma1/Melodist"
    machines = ["windows.amd64"]

    // Entrada principal de la app compilada
    inputs = ["composeApp/build/compose/jars/*.jar"]

    jvm {
        gui.main-class = "com.example.melodist.MainKt"
        include-all-modules = true

        modules += "java.sql"  // 👈 ESTA ES LA CLAVE

        args = [
            "--add-modules=java.sql",
            "-XX:+EnableDynamicAgentLoading",
            "-Xmx512m",
            "-Xms128m",
            "-XX:+UseG1GC",
            "-XX:MaxGCPauseMillis=50",
            "-XX:+UseStringDeduplication",
            "-XX:+UseCompressedOops",
            "-XX:MaxMetaspaceSize=128m",
            "-XX:+ExitOnOutOfMemoryError"
        ]

        system-properties."compose.application.resources.dir" = "."
        system-properties."org.sqlite.tmpdir" = "${user.home}/.melodist/tmp"
    }

    site {
        github {
            oauth-token = ${env.conveyor_token_melodist}
            pages-branch = "gh-pages"
        }
    }
}

windows {
    formats = ["msix", "zip", "exe", "msi"]

    // 👇 ESTA LÍNEA ES CLAVE
    enable-exe = true
    enable-msi = true

    menu-group = "Melodist"
    desktop-shortcut = true
    per-user-install = true
    allow-custom-install-dir = true
    upgrade-uuid = "4A2F8B6C-1D3E-4F5A-B7C8-9D0E1F2A3B4C"

    app-resource-dirs = ["vlc-resources/windows"]
}

gradle.main-module = "composeApp"
