include "/stdlib/jdk/21/jetbrains.conf"

conveyor.compatibility-level = 22
conveyor.billing-email = "andrestormenta1@gmail.com"

app {
    display-name = "Melodist"
    fsname = "melodist"
    version = "1.0.5"
    vendor = "Tarma"
    description = "Reproductor de música de escritorio"
    rdns-name = "com.example.melodist"

    vcs-url = "github.com/AndresTarma1/Melodist"
    machines = ["windows.amd64"]

    // Entrada principal de la app compilada
    inputs = [
        "composeApp/build/compose/jars/Melodist-windows-x64-1.0.5.jar",
        {
            from = "mpv-resources/windows/libmpv-2.dll"
            to = "libmpv-2.dll"
        }
    ]

    jvm {
        gui.main-class = "com.example.melodist.MainKt"
        
        // Módulos optimizados para reducir el peso drásticamente
        modules = [ 
            java.base, java.desktop, java.sql, java.management, 
            java.naming, java.prefs, java.xml, jdk.unsupported, 
            java.instrument, jdk.jfr, jdk.crypto.ec, java.net.http
        ]

        args = [
            "-XX:+EnableDynamicAgentLoading",
            "-Xmx512m",
            "-Xms128m",
            "-XX:+UseG1GC"
        ]

        // Importante para las rutas dinámicas en producción
        system-properties."compose.application.resources.dir" = "."
    }

    site {
        github {
            oauth-token = ${env.conveyor_token_melodist}
            pages-branch = "gh-pages"
        }
    }
}

windows {
    formats = ["exe", "msi", "msix"]

    enable-exe = true
    enable-msi = true

    menu-group = "Melodist"
    desktop-shortcut = true
    per-user-install = true
    allow-custom-install-dir = true
    upgrade-uuid = "4A2F8B6C-1D3E-4F5A-B7C8-9D0E1F2A3B4C"
}

gradle.main-module = "composeApp"
